### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by guillemj** [ncabatoff/fakescraper#2]
This code does not have a license so it is not really redistributable by others. It would be nice to declare this so that it can be packaged for Debian for example, now that the this has been unvendored from the prometheus-process-exporter. :)

**Comment by fabioasdias** [comment]
Pretty please? Otherwise I'll have to either fork process exporter and remove it as dependency or just figure out some other service to use instead. I really don't need either on my backlog, please have mercy :)

**Comment by guillemj** [comment]
@fabioasdias we ended up removing it from our prometheus-process-exporter package in Debian, the description on the patch is probably not accurate, as at least I'd gladly package it if it was possible, but all the same. Here's the patch in case it might be of help: https://salsa.debian.org/go-team/packages/prometheus-process-exporter/-/blob/debian/sid/debian/patches/03-disable-fakescraper.patch
